### ISSUE TITLE
Work flow issue

### ISSUE THREAD

**Issue by kiddkid99** [chiayi50446/ASP_NET_MVC_Q1#5]
1. 可以簡化流程為
Detail -> (POST) Check -> (POST) Save

2. 可以不需要用到 TempData

**Comment by chiayi50446** [comment]
1. 我已試著簡化流程，但不確定是否符合要求
2. 已修正

**Comment by kiddkid99** [comment]
簡化流程的做法是對的，再把 Save Action 限制只能使用 Http Post 就可以了

**Comment by chiayi50446** [comment]
OK
已修正
